### ISSUE TITLE
Absurd-Sql

### ISSUE THREAD

**Issue by twoxfh** [WebReflection/sqlite-worker#11]
It appears indexeddb is being written to all at once [here](https://github.com/WebReflection/sqlite-worker/blob/9d344d8eec2c908b3cf2bdcfe3f0c4a2ff3de147/esm/init.js#L8). The Absurd-Sql, based on SQL-JS, project also uses it [here](https://github.com/jlongster/absurd-sql/blob/38702f0d9b4290d0ebecbbf0ebf3a48fd6b0c893/src/indexeddb/worker.js#L303), possibly there are some performance gains since it writes in blocks opposed to all at once.

**Comment by WebReflection** [comment]
> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

not sure what I am looking at, but also I am not sure I care much ...

Jan 9, 2021 is the first commit for his project, while 6 months later, Jun 28, 2021 the first commit for that project landed on GitHub.

I've been there before, down the not-contributing-road, and I don't need this kind of stress these days.

If you prefer that project instead, use that project instead 👍

**Comment by twoxfh** [comment]
Was not sure if you would be interested in a pull request of this kind or if any other thoughts around it had already been percolating. Certainly understand your stance on stale projects. Thanks for the feedback.

**Comment by WebReflection** [comment]
> Was not sure if you would be interested in a pull request of this kind

I couldn't *infer* that from your filed issue, but if you think you could do that, please go ahead, as I always welcome great ideas, which is why I am sad when "*everything already there was working but I created a new thing*" projects happen, like the one you mentioned in the first place.
