### ISSUE TITLE
Access to DB instance from the worker?

### ISSUE THREAD

**Issue by kikohs** [WebReflection/sqlite-worker#14]
Hello,
Thank you for creating this package!

Could it be possible to have access to the DB instance from the worker?
Thanks

**Comment by WebReflection** [comment]
I am not sure I understand this question ... the DB is loaded into memory and saved via IndexedDB, what access to DB instance means here?

**Comment by kikohs** [comment]
I meant the ability to run db.run(...,..); So probably the indexed DB instance.
`const rows = db.exec(sql, params);`

**Comment by WebReflection** [comment]
run is query here ... have you checked the API? https://github.com/WebReflection/sqlite-tag#api

I still don't understand your question: this module uses sqlite WASM via IndexedDB and it's based on the mentioned API

**Comment by kikohs** [comment]
I'm integrating your package into cables.gl (low-code node based visual coding) where users can run arbitrary queries. I'm trying to find a way to use the safe (?) (?) (?) replacement parameters to avoid SQL injection but can't when the query is not know in advance.

**Comment by WebReflection** [comment]
you might try this? https://github.com/WebReflection/tag-params

otherwise consider template literals tags are just functions:

```js
query('INSERT INTO table (one, two, three) VALUES (?, ?, ?)'.split('?'), ...[1, 2, 3]);
```

**Comment by kikohs** [comment]
Great!! Exactly what I wanted.
Thank you
