### ISSUE TITLE
How to build sqlite WASM

### ISSUE THREAD

**Issue by ramezrafla** [WebReflection/sqlite-worker#15]
Thanks so much @WebReflection for the only sqlite in JS that works easily with modern bundlers (we tried all the other libraries and always faced an issue somewhere).

At the heart of this implementation is the custom WASM build. The bundled sqlite build is 3.36.0 while current latest is 3.46.0. 

Any chance you can share your emcc build script or command-line?

Happy to PR this repo with updated build.

**Comment by WebReflection** [comment]
The thing I need to do is to track the dependencies, update these, `npm run build` and it’s done … this project just re-package what’s already out there

**Comment by ramezrafla** [comment]
Thanks @WebReflection -- would be very grateful. If you are busy, just point to the project where WASM was built and I'll PR.

**Comment by WebReflection** [comment]
Aha ... I got confused with https://github.com/WebReflection/sql.js which is my latest/greatest wrapper for `sql.js` where stuff just works anywhere (workers too) but it doesn't offer all features we have in here.

I have updated to latest *sql.js* in here and published as `0.9` ... please let me know if something broke, thanks.

**Comment by ramezrafla** [comment]
@WebReflection -- thanks so much! Well done!

The new WASM and its JS file are working perfectly (SQLite v 3.45.2) -- as a bonus the binary buffer worked right away from previous version.

Just note that we are using our own worker / bridge based on this library as we couldn't import with our bundler (vite-js -- location of worker / wasm remains a pain point for bundlers) so can't speak on whether there are issues there, but don't foresee the change in SQLite version to cause any harm.

Will go through the sql.js repo now to do a deep dive and see if we can repeat the build.

This library is a life-saver, thanks so much!
