### ISSUE TITLE
Errors in both Firefox and Chrome on MacOS

### ISSUE THREAD

**Issue by mikeptweet** [WebReflection/sqlite-worker#3]
![image](https://user-images.githubusercontent.com/1769876/104171701-9c4b7200-53dd-11eb-924e-db6f35feb041.png)

From your test site, I get these errors in the console.

**Comment by WebReflection** [comment]
**expected** is not there by accident ... the live test page does full code coverage, including error handling.

However, the page doesn't have any error in Chrome, but it does have one error in both Firefox and WebKit/Safari, and this has been explained in the readme.

https://github.com/WebReflection/sqlite-worker#-warning-about-workers

Long story short: use `init` and ignore the worker export/version of this module, as browsers are very confused in how dynamic import is used by developers.

**Comment by WebReflection** [comment]
P.S. you can test the `init` export, without errors, in all modern browsers here:
https://webreflection.github.io/sqlite-worker/test/init.html

**Comment by mikeptweet** [comment]
Much appreciated ... thanks

**Comment by WebReflection** [comment]
FYI v0.4 works everywhere 🎉
