### ISSUE TITLE
Problem injecting into query

### ISSUE THREAD

**Issue by javieranton-zz** [WebReflection/sqlite-worker#7]
Hi,

For some reason, the following throws an error:

```
let table = 'todos';
await all`SELECT * FROM ${table} `
```

It seems strings can't be injected into backtick quotes when querying, but they do work when executing. Am I doing something wrong?

Thanks

**Comment by javieranton-zz** [comment]
So I debugged and found that `all` doesn't parse arguments. I'm not a js wizard so can't say what is wrong. What I know is that if I replace `index.js`'s code with this it works:

```
//for query `SELECT * FROM ${'todos'} WHERE value = '${'a'}'`
                       all(t){ 
                            console.log(t);
                            console.log(arguments);
                            //0: (3) ["SELECT * FROM ", " WHERE value = ", "", raw: Array(3)]
                            //1: "todos"
                            //2: "a"
                            let finalQuery = arguments[0][0];
                            for(let iter = 1; iter< arguments[0].length; iter++){
                                finalQuery += arguments[iter];
                                finalQuery += arguments[0][iter];
                            }
                            console.log("final query: "+finalQuery);
                            return u([finalQuery]);
                        }
```

Hope this helps, feel free to close

**Comment by WebReflection** [comment]
You can't create raw parts of the query unless you use the `raw` utility, see:
https://github.com/WebReflection/sqlite-tag#api

the `raw` utility is also not possible via Worker, you need a direct handler, as described in here:
https://github.com/WebReflection/sqlite-worker#after-initialization-helpers

Alternatively, you can use [static-params](https://github.com/WebReflection/static-params#readme) to implement your raw helper anywhere you like, including the worker.

In few words, you have discovered that this module is not SQLInjection prone by default.

**Comment by javieranton-zz** [comment]
Thanks. This module is very good, thanks for sharing it. I hope I will be able to modify it to run dynamic SQL

**Comment by javieranton-zz** [comment]
Am I right in thinking that [sqlite-tag](https://github.com/WebReflection/sqlite-tag#api) is only meant to be used server-side?

**Comment by WebReflection** [comment]
There is a [live demo and Code Pen demo](https://github.com/WebReflection/sqlite-worker#compatibility) in the README, so you're wrong?

**Comment by javieranton-zz** [comment]
I tried using static-params and got this far:

```
const staticStatement = asStatic("DELETE FROM todos WHERE value = 'a'");
await query `${staticStatement}`;
```

But it seems the template still isn't accepted

`Uncaught (in promise) near "?": syntax error`

Apologies for using your valuable time, I will keep digging

**Comment by javieranton-zz** [comment]
The reason why I asked whether [sqlite-tag](https://github.com/WebReflection/sqlite-tag#api) is server-side is that it requires [sqlite3](https://www.npmjs.com/package/sqlite3), which is a node/electron package

**Comment by javieranton-zz** [comment]
Got it!

Winning combination was

`await query `DELETE FROM todos WHERE value = '${asStatic('a')}'`;`

Thanks!

**Comment by javieranton-zz** [comment]
I managed to get it working. It's pretty disappointing to see how IndexedDB isn't really reliable, at least not yet. Hope it will improve with time. Thanks for the help

**Comment by WebReflection** [comment]
Glad you managed! It made me realize the raw utility somehow *should* work via worker too … I’ll think about it, and find a way to make it happen.

**Comment by javieranton-zz** [comment]
Awesome :-D

**Comment by WebReflection** [comment]
@javieranton-zz the `raw` utility is now available via *Worker* instances too. This should simplify your code, providing 1:1 API between initializations.

**Comment by javieranton-zz** [comment]
Wow, so quick, thank you!

Just tested and getting the error `plain is not defined` coming from 
https://github.com/WebReflection/sqlite-worker/blob/main/dist/index.js

Seems `plain` is not defined before it's used? The test folder works, but could it be that it ins't using the new worker's raw utility?

**Comment by WebReflection** [comment]
The test folder has been updated to use the raw utility ... that's very weird ...

**Comment by WebReflection** [comment]
@javieranton-zz gotcha, fixed!

**Comment by javieranton-zz** [comment]
So cool!

Here is one last idea from me: Currently the templates still need to have their beginning hard-coded.

For example, the following is ok:

```
await query`CREATE TABLE IF NOT EXISTS ${raw`${tableName}`} (${raw`${fields}`})`;
```

But the following isn't:

```
let createQuery = "CREATE TABLE IF NOT EXISTS TEST54 (Property text not null,Value text not null)";
await query`${createQuery}`;
```

Your tool is extremely valuable to me because I am migrating an app to the web that currently uses sqlite on Android, iOS and Windows. As such I already have all the transactions ready to be fed into the DB.

But because the beginning of each sentence needs to be hard-coded I will have to manually parse each transaction and call its respective js function that calls CREATE/INSERT/SELECT etc

It would be awesome if the entire query could be injected, not just the last part

But I am ever so happy with this as it is, so thanks! I will make sure to mention your repository during release

**Comment by WebReflection** [comment]
That's a SQL injection hazard, and no way I'll make it default here. Just use `raw`.

```js
let createQuery = raw("CREATE TABLE IF NOT EXISTS TEST54 (Property text not null,Value text not null)");
await query`${createQuery}`;
```

**Comment by WebReflection** [comment]
Alternatively, just use the template literal tag signature:

```js
await query([
  "CREATE TABLE IF NOT EXISTS TEST54 (Property text not null,Value text not null)"
]);
```

**Comment by WebReflection** [comment]
A **tag** is a function with the following signature:

```js
function tag(template:string[] , ...values:any[]) {
}
```

If you pass an array with one single entry that's a template with no values.

I hope this helps, yet watch out SQL injections, and never pass values directly, or it'll fail/don't work as expected.

**Comment by javieranton-zz** [comment]
Oh, I hadn't realized I still was missing `raw` ':-)

**Comment by WebReflection** [comment]
Also, to be honest, this would just work:

```js
await query`CREATE TABLE IF NOT EXISTS TEST54 (Property text not null,Value text not null)`;
```

so you have all options in here.

**Comment by javieranton-zz** [comment]
Hey, I was just thinking...

I can't stop thinking about how much of a game-changer this library is. We finally are able to do all sorts of SQL magic on web apps, with persistence!

One of the  problems I've encountered with this module is that when you delete all the records in one table, a `CREATE` query must precede any further `INSERT`s. It's like the DB forgets all about any table that ever existed as soon as all of the records within it are gone

To get around this, I am hard coding individual `CREATE` scripts for each and every table I ever expect to use, and when I get a "no such table" error while attempting an `INSERT`, I then detect which table the `INSERT` was targeting and run its `CREATE` script again before re-attempting the `INSERT`

Hope I haven't lost you, I'm not very good with words

I am wondering about whether it is possible to integrate some measure into this library so that this work-around isn't necessary. Just sharing this thought

**Comment by WebReflection** [comment]
> Hope I haven't lost you, I'm not very good with words

You did ... I understand code better than words ... any example?

P.S. `sqlite-worker/table` might be the answer ... try that, it creates/modify on the go

**Comment by WebReflection** [comment]
P.S. multiple workers cannot share the same DB ... don't ever do that, as each DB is stored in memory.

**Comment by javieranton-zz** [comment]
> P.S. multiple workers cannot share the same DB ... don't ever do that, as each DB is stored in memory.

How can I reuse the same worker? Each call to `SQLiteWorker` creates a new worker

**Comment by javieranton-zz** [comment]
OK, I think I found some problem.

The following works only via `worker`, (it doesn't work via `init`):
```
await query`CREATE TABLE IF NOT EXISTS someTable (Property text not null,Value text not null)`;
let insertQuery = "INSERT OR IGNORE INTO someTable (Property, Value) VALUES ('l','s')";
await query`${raw`${insertQuery}`}`;//init doesn't like this (but worker does)
```
In order to make it work via `init`, the `query` needs to be passed the whole insert, not just a string via raw:

```
await query`CREATE TABLE IF NOT EXISTS someTable (Property text not null,Value text not null)`;
let insertQuery = "INSERT OR IGNORE INTO someTable (Property, Value) VALUES ('l','s')";
await query`${raw`${INSERT OR IGNORE INTO someTable (Property, Value) VALUES ('l','s')}`}`;//both init and worker like this
```

**Comment by javieranton-zz** [comment]
Also, the issue that requires spacing separate transactions apart 500ms remains even after only using `init` and not `workers` (this is ok, it likely has nothing to do with this module)

**Comment by WebReflection** [comment]
I am not sure what you mean, because I've used transaction heavily before and never had this issue.

With sql.js I'd go like:

```js
await query`BEGIN TRANSACTION`;
await Promise.all([
  query`INSERT INTO table VALUES (${Math.random()})`;,
  // all other operations
]);
await query`END TRANSACTION`;
```

It's true that my experience is with synchronous SQLite there though, but if you could give me an example that requires such delay, I might try to figure out a solution.

**Comment by WebReflection** [comment]
Btw, the whole purpose of this module and sqlite-tag syntax is to avoid `VALUES ('l','s')` stuff like that.

Why don't you just use `query` as it's meant to be used? It looks like you are abusing `raw` all over, and I am not sure I want to support this pattern at all, specially when values are hard coded in quotes ... that's not how anyone should write SQL, no matter the library used.

**Comment by javieranton-zz** [comment]
> Btw, the whole purpose of this module and sqlite-tag syntax is to avoid `VALUES ('l','s')` stuff like that.
> 
> Why don't you just use `query` as it's meant to be used? It looks like you are abusing `raw` all over, and I am not sure I want to support this pattern at all, specially when values are hard coded in quotes ... that's not how anyone should write SQL, no matter the library used.

I only wrote the query like that so that it could be easier to understand. `init`' and `workes`'s `query`s accept different params. You yourlsef said that 

```
await query`${raw`${someVar}`}`;
```

should work, but this is only true for `worker`. I am satisfied because it appears that "template literal tag signatures" work with `init` i.e.:

```
await query([someVar]);
```

So this is enough for me. But I am just warning you that `worker` and `init` behave different.

**Comment by javieranton-zz** [comment]
> I am not sure what you mean, because I've used transaction heavily before and never had this issue.
> 
> With sql.js I'd go like:
> 
> ```js
> await query`BEGIN TRANSACTION`;
> await Promise.all([
>   query`INSERT INTO table VALUES (${Math.random()})`;,
>   // all other operations
> ]);
> await query`END TRANSACTION`;
> ```
> 
> It's true that my experience is with synchronous SQLite there though, but if you could give me an example that requires such delay, I might try to figure out a solution.

I know, I know. Multiple `INSERTS` should be bundled and executed within the same transaction. But the "issue" I am referring to affects the case where multiple `INSERTS` are executed consecutively in _different_ transactions. It's not a big deal, please don't  worry about this. I don't think there is anything we can do anyway since this affects sqlite3 in multiple platforms (except Android and Java and perhaps others where sqlite3 seems to have some sort of first class citizen status)
