### ISSUE TITLE
OOM

### ISSUE THREAD

**Issue by javieranton-zz** [WebReflection/sqlite-worker#9]
Hi,

I am load testing and have noticed that the following happens when a row containing a single 1.3MB blob is written:

```
RuntimeError: memory access out of bounds
RuntimeError: table index is out of bounds
    at sql-wasm.wasm:0x36f48
    at sql-wasm.wasm:0x4259e
    at sql-wasm.wasm:0xb8643
    at za (sql-wasm.wasm:0xfa419)
    at e._sqlite3_close_v2 (VM26073 sql-wasm.js:2791)
    at c.export (VM26073 sql-wasm.js:420)
    at index.js:103
    at new Promise (<anonymous>)
    at index.js:102
```

This is possible on other sqlite3 implementations so I wonder if there is anything that can be done to make it work here as well

Many thanks

> Edit: I originally posted 8.4MB but then found it happens also with as little as 1.3MB. I know it doesn't happen with 1MB, somewhere between 1MB and 1.3MB it hits a limit. This was tested on Chrome (Opera)

**Comment by WebReflection** [comment]
sounds like a bug for sql.js as here nothing deals with any memory size limitation so there's likely nothing I can do?
https://github.com/sql-js/sql.js

**Comment by WebReflection** [comment]
P.S. without a use case to reproduce, without knowing which browser it is, without knowing if it's via worker or main, ... without knowing anything, it's impossible to also debug this, so I'll close as this cannot be worked on my side by any mean.

**Comment by javieranton-zz** [comment]
As I said, the browser is Chrome (Opera). Tested via main. Use case would be as simple as trying to run a write query that writes a string longer than 1MB (1,000,000 characters)

If it's a sql.js problem then don't worry about it

I am working on a workaround that detects these cases and splits the queries into partial UPDATEs. I'll let you know if this works

**Comment by WebReflection** [comment]
> Use case would be as simple as trying to run a write query that writes a string longer than 1MB (1,000,000 characters)

yeah, but I have little time these days, so any pre-made failing example would surely help ... or better, I won't work on issues that don't provide test cases in general, as I have too many things going on these days.

Happy to have a look through an example though, but I have no hard limit set anywhere in here, so I don't think I can fix it in a ny way.

**Comment by javieranton-zz** [comment]
Sure, no problem. Not trying to waste your time, just thought you might have a pre-made test case with a string. But here is the code that would throw this error:

window.initSQL({name: 'SomeDB'}).then(async ({all, get, query, raw}) => {
    await query`CREATE TABLE IF NOT EXISTS SomeTable (field text)`; 
    let longText = "";
    for(let i = 0; i< 100000; i++)//this will build up a 2MB string
         longText += "20        characters";
    let writeQuery = "INSERT INTO SomeTable (field) VALUES ('"+longText +"')";
    await query([writeQuery]);//this will break
});

**Comment by WebReflection** [comment]
thanks, but why do you keep writing SQL injection prone code though?

have you tried this instead? this is **how you should write queries with this module**

```js
initSQL({name: 'SomeDB'}).then(async ({all, get, query, raw}) => {
    await query`CREATE TABLE IF NOT EXISTS SomeTable (field text)`; 
    const longText = "20        characters".repeat(100000);
    await query`INSERT INTO SomeTable (field) VALUES (${longText})`;
    await query([writeQuery]);//this will break
});
```

**Comment by javieranton-zz** [comment]
Very interesting, and thank you for taking your time to walk me through this. 

> why do you keep writing SQL injection prone code though

I am not concerned about injection hazards because this is purely a client app and the local DB doesn't contain any sensitive information. If the client decides to mess up his own local DB that is fine. The local DB is only a copy of an online repository that has 0 relation with server side functionality. Even if a client decided to artificially increase his local DB and push that to their cloud copy, that is also fine, as they have to pre-pay for cloud storage

With this knowledge in mind I can now make use of the template to prevent these problems. It was just simpler for me to feed the entire query through as that is the form it comes in from the repository. Thanks again

**Comment by WebReflection** [comment]
It’s not a client/server issue, it’s how any database related operation should be performed. There is no circumstance where concatenating strings, to provide values, is the way to go fit every possible reason, including data type, SQLite injection, driver SQL parsing overhead, you name it.

do not ever do that anywhere, and use the right tool to do operations the right way.

**Comment by javieranton-zz** [comment]
I appreciate the advise. In my use case, I need to process literally any type SQL statement. I have no previous knowledge of what it can be. So building templates for that is not as straight forward, but can be done with a bit of extra work

**Comment by WebReflection** [comment]
If queries come with values, it’s trivial to remove at least strings, return a ?, split by ?, use that as template, and spread all strings as interpolations … now, I don’t know what kind of escape you have there, but it’s valid SQLite, looking for ' and skip intermediate '' sequences, if any, before the next ' should work already

**Comment by javieranton-zz** [comment]
If you find the time, would you mind showing an example of how the following query can be converted into a template by the means you described? Sorry to bother you, I will understand if you don't :-)

`let query = "INSERT INTO Sometable (field1,field2) VALUES ('Value1','Value2')";`

**Comment by WebReflection** [comment]
something like this should work:

```js
const asTemplateArguments = query => {
  const template = [];
  const args = [template];
  const {length} = query;
  let open = false;
  let i = 0;
  let k = 0;
  while (k < length) {
    switch (query[k++]) {
      case "'":
        if (!open) {
          open = true;
          template.push(query.slice(i, k - 2));
          i = k;
        }
        // skip double single-quotes
        else if (k < length && query[k] === "'") {
          k++;
        }
        else {
          open = false;
          args.push(query.slice(i, k - 1).replace(/''/g, "'"));
          i = k;
        }
        break;
    }
  }
  template.push(query.slice(i, k));
  return args;
};

let sql = "INSERT INTO Sometable (field1,field2) VALUES ('Value1','Value2')";

await query(...asTemplateArguments(sql));
```

**Comment by WebReflection** [comment]
P.S. mind the edit

**Comment by javieranton-zz** [comment]
Thank you ever so much, it works. Do you think I should be doing the same for UPDATEs and DELETEs?

**Comment by WebReflection** [comment]
I don’t know what you’re doing. If you are importing a dump once then yes, if you’re planning to execute that each time then I’d ask why … I mean, a one off dump makes sense, but I am pretty sure you don’t have thousands selects, delete, or updates SQL, you can rewrite those as templates and pass dynamic values instead?

**Comment by javieranton-zz** [comment]
Yes, I mostly meant dumps. Just wanted to know your opinion on the safety of using/not using templates for those things (I still don't understand what it means to be "unsafe" in this context. For example, what can the consequences be of not using a template for a SELECT etc)

Thanks

**Comment by WebReflection** [comment]
for dumps you can use that helper (and should) for every operation.

about safe, you got bitten already by misusing the SQLite driver, so I suggest you avoid passing plain strings around every time you can, including SELECTS, as these might reach that parsing hard limit for SQL strings already.

```sql
--- this is GOOD!
SELECT id FROM book WHERE sentence LIKE ?

--- this SUCKS!
SELECT id FROM book WHERE sentence LIKE '%nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope nope%'
```

**Comment by javieranton-zz** [comment]
OK, got it

I will try to tweak your code to make sure the below query doesn't break (I think the hex field needs something special)

`Error: near "?": syntax error. Original query: INSERT OR IGNORE INTO HiddenLinks (Id,SourceId,TargetId) VALUES (X'8E66A9A4225852717B8B7955D23FFC8E',X'F498AE602584A3FABE8C1282EB9AF8A5',X'8EFF4DB423AAA432130EAC6DFE2A170F')`

**Comment by WebReflection** [comment]
Rule of thumbs (last comment from my side):
  * should I always use the template literal way with interpolations within it for values? **Yes**
  * should I avoid at all costs passing concatenated strings or any SQL that contains strings as value within the statement? **Also Yes**.

Like I've said, there is not a single use case for *not* using `?` when values are meant ... there's no maybe, there's no statement, if you have a value, the value should never be there, a `?` should be there instead.

**Comment by WebReflection** [comment]
> I think the hex field needs something special)

I've no idea what's the X field there but it's clearly not part of my helper, as I wrote that in a minute and it surely doesn't cover the world ... you can improve that though 👋

**Comment by javieranton-zz** [comment]
It's a GUID field.. part of the original query. Sorry for having taken so much of your time, have a good one

**Comment by WebReflection** [comment]
P.S. it is also very possible with `X` use case you need to ignore it as the `?` won't work there.

this might do the trick:

```js
const asTemplateArguments = query => {
  const template = [];
  const args = [template];
  const {length} = query;
  let open = false;
  let i = 0;
  let k = 0;
  while (k < length) {
    switch (query[k++]) {
      case "'":
        if (!open) {
          if (/x/i.test(query[k - 2])) {
            k = query.indexOf("'", k) + 1;
            continue;
          }
          open = true;
          template.push(query.slice(i, k - 1));
          i = k;
        }
        // skip double single-quotes
        else if (k < length && query[k] === "'") {
          k++;
        }
        else {
          open = false;
          args.push(query.slice(i, k - 1).replace(/''/g, "'"));
          i = k;
        }
        break;
    }
  }
  template.push(query.slice(i));
  return args;
};
```

**Comment by javieranton-zz** [comment]
Works like a charm :-)

I was still able to reproduce 1 OOM error when processing things like this, but it was only after processing 50MB worth of queries and only thrown by 1 query

```
Uncaught (in promise) RuntimeError: table index is out of bounds
    at sql-wasm.wasm:0x36f48
    at sql-wasm.wasm:0x4259e
    at sql-wasm.wasm:0xb8643
    at za (sql-wasm.wasm:0xfa419)
    at e._sqlite3_close_v2 (VM45815 sql-wasm.js:2791)
    at c.export (VM45815 sql-wasm.js:420)
    at index.js:103
    at new Promise (<anonymous>)
    at index.js:102
```

The query in question was 1.4MB long and is pasted below (omitting long chars in between). It wasn't the largest query by far, as there had been several successful >8MB processed below

`INSERT OR IGNORE INTO Documents (Id,SourceMemberId,Name,Format,Size,Data) VALUES (X'6CA68132F173E791CB075FBD5734FCA1','6903DCCB16346BE789FB1F743DD0D205','History.pdf','pdf','1061839',"JVB...........................not copying the entire base64 string here")--*IGNORE_SQL*`

I guess I will still have to implement a mechanism to break up large inserts into 1 INSERT + Array of UPDATEs. You be off!

**Comment by javieranton-zz** [comment]
Oh wait a minute, just realised that articular query was using double quotes for one field :-S

**Comment by javieranton-zz** [comment]
A modified version of your code that  handles both single and double quotes, including the case where they live inside each other (i.e. '"..."' or "'...'")

```
const asTemplateArguments = query => {
      const template = [];
      const args = [template];
      const {length} = query;
      let openSingleQuotes = false;
      let openDoubleQuotes = false;
      let i = 0;
      let k = 0;
      while (k < length) {
        switch (query[k++]) {
          case "'":
            if(!openDoubleQuotes){
                if (!openSingleQuotes) {
                  if (/X/.test(query[k - 2])) {
                    k = query.indexOf("'", k) + 1;
                    continue;
                  }
                  openSingleQuotes = true;
                  template.push(query.slice(i, k - 1));
                  i = k;
                }
                // skip double single-quotes
                else if (k < length && query[k] === "'") {
                  k++;
                }
                else {
                  openSingleQuotes = false;
                  args.push(query.slice(i, k - 1).replace(/''/g, "'"));
                  i = k;
                }
                break;
            }
          case "\"":
            if(!openSingleQuotes){
                if (!openDoubleQuotes) {
                  if (/X/.test(query[k - 2])) {
                    k = query.indexOf("\"", k) + 1;
                    continue;
                  }
                  openDoubleQuotes = true;
                  template.push(query.slice(i, k - 1));
                  i = k;
                }
                // skip double double-quotes
                else if (k < length && query[k] === "\"") {
                  k++;
                }
                else {
                  openDoubleQuotes = false;
                  args.push(query.slice(i, k - 1).replace(/""/g, "\""));
                  i = k;
                }
                break;
            }
        }
      }
      template.push(query.slice(i));
      return args;
    };
```

**Comment by WebReflection** [comment]
AFAIK SQLite deals/prefers single quotes so I am not sure why the double quote is needed ... but glad you solved.

Have a nice weekend 👋

**Comment by javieranton-zz** [comment]
Thanks man, you too have a nice weekend wherever you are. Thanks again for your help. One fringe type of query wrongly used double quotes for one field... that is now everywhere so need to account for that

I am sure you could improve it ;) but mortals need to live with what "just works"

**Comment by WebReflection** [comment]
@javieranton-zz you made me laugh, but I swear I'm mortal too ... anyway, this is the simplification I had in mind, and one of the reasons I love JS too ;-)

```js
const asTemplateArguments = query => {
  const loop = quote => {
    if (!open) {
      if (/X/.test(query[k - 2])) {
        k = query.indexOf(quote, k) + 1;
        return;
      }
      open = true;
      template.push(query.slice(i, k - 1));
      i = k;
    }
    else if (k < length && query[k] === quote) {
      k++;
    }
    else {
      open = false;
      args.push(query.slice(i, k - 1).replace(
        new RegExp(quote + quote, 'g'),
        quote
      ));
      i = k;
    }
  };
  const template = [];
  const args = [template];
  const {length} = query;
  let open = false;
  let i = 0;
  let k = 0;
  while (k < length) {
    switch (query[k++]) {
      case "'":
      case '"':
        loop(query[k - 1]);
        break;
    }
  }
  template.push(query.slice(i));
  return args;
};
```

**Comment by javieranton-zz** [comment]
I'm glad... seems I haven't completely lost my sense of humor then :-D

Really cool how you can simplify/optimize code in js like this. The new code works but fails for the case of double quotes contained within single quotes. For example, the following query fails;

`INSERT OR IGNORE INTO SomeTable (Payload) VALUES ('{"Order":"150"}')`

Thanks

**Comment by WebReflection** [comment]
fair enough, but the edited version should work: https://github.com/WebReflection/sqlite-worker/issues/9#issuecomment-889913505

**Comment by javieranton-zz** [comment]
![4NC](https://user-images.githubusercontent.com/11293898/127670449-e85f9d56-afc0-431f-a6c4-0562a87e2793.gif)
Awesome Andrea, I am in awe! :-D

**Comment by WebReflection** [comment]
@javieranton-zz FYI I've fine-tuned the logic around `asTemplateArguments` which is now faster and smaller than ever: https://github.com/WebReflection/sqlite-worker/issues/9#issuecomment-889913505

**Comment by javieranton-zz** [comment]
Nice one! Tested and it works great
